### PR TITLE
Add some more conditional styling and transitions to the image feed

### PR DESCRIPTION
**Pull request by DrJKL**
I think it could still use some work.

Resize on change instead of input to avoid input jank when changing the size at left or right
I think if the controls were in a menu instead of on the component that would fix the issue.

The interaction between feed size and image size also still feels unintuitive to me.

### CODE REVIEW

**Comment by DrJKL** [comment]
[scrnli_7_17_2023_3-21-37 PM.webm](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/448862/e66fd7d9-144f-45f3-a76f-1134e6497e66)

**Comment by DrJKL** [comment]
Do you have any other ideas for how this could be improved?

**Comment by pythongosssss** [comment]
Sorry for lack of feedback on this!
I'm not really sure... I personally like the resizing done on input rather than change as when swapping between different image sizes/browser sizes I like to resize it to the "perfect" point which is hard to do without instant feedback

Maybe as you said moving the inputs into a menu would be the best fix for it, a little settings cog that when you hover over it pops up a menu with the two sliders on in a fixed position based on where it opened.

Agreed about the feed and image size behavior, but I couldn't get anything that didnt feel a bit weird working!

**Comment by DrJKL** [comment]
How would you feel about the images slider being a "number of columns"?
Or it could be the image size is a width, the number of columns (left/right) or rows (top/bottom) would define the size of the feed.

**Comment by DrJKL** [comment]
Okay, I think this is a bit nicer.

https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/448862/6f3f567d-28f3-467e-b8c7-2d11176da244

**Comment by DrJKL** [comment]
I still think making the image size a discrete "number of columns" would be cleaner.

**Comment by pythongosssss** [comment]
Yeah, I like this one, works really well - good job, thank you.
I'm not opposed to it being a number of columns if that works better, but what you've got here is nice

**Pull request merged**
